server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mybatis
    username: root
    password: 1277560510
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service #应用名称，注册到eureka后的服务名称
mybatis:
  type-aliases-package: cn.itcast.service.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1  # 指定自己的ip信息，不指定的话会自己寻找
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称